--- !ruby/struct:Cukedep::Config
feature_encoding: UTF-8
proj_dir: 
feature2id: !ruby/struct:Cukedep::FileMetaData
  name: feature2id.csv
id2feature: !ruby/struct:Cukedep::FileMetaData
  name: feature2id.csv
graph_file: !ruby/struct:Cukedep::FileMetaData
  name: dependencies.dot
rake_file: cukedep.rake
cucumber_args: []
before_all_f_actions:
  :save_patterns: []
  :save_subdir: ''
  :delete_patterns: []
  :delete_subdir: ''
  :copy_patterns: []
  :copy_subdir: ''
before_each_f_actions:
  :save_patterns: []
  :save_subdir: ''
  :delete_patterns: []
  :delete_subdir: ''
  :copy_patterns: []
  :copy_subdir: ''
after_each_f_actions:
  :save_patterns: []
  :save_subdir: ''
  :delete_patterns: []
  :delete_subdir: ''
  :copy_patterns: []
  :copy_subdir: ''
after_all_f_actions:
  :save_patterns: []
  :save_subdir: ''
  :delete_patterns: []
  :delete_subdir: ''
  :copy_patterns: []
  :copy_subdir: ''
