language: ruby
rvm:
  - 2.5.0
  - 2.4.2
  - 2.3.5
  - 2.2.8
  - jruby-head
  - jruby-9.1.9.0
  - ruby-head  

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head

gemfile:
  - Gemfile

# whitelist
branches:
  only:
    - master