language: ruby
rvm:
  - 2.6.0
  - 2.5.3
  - 2.4.5
  - 2.3.8
  - 2.2.10
  - jruby-9.1.9.0
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head

gemfile:
  - Gemfile

# whitelist
branches:
  only:
    - master